dbt-taxi-demo:
  target: dev
  outputs:
    dev:
      type: glue
      query-comment: demo-nyctaxi
      role_arn: "arn:aws:iam::253491126433:role/GlueInteractiveSessionRole"
      region: us-east-1
      workers: 2
      worker_type: G.1X
      schema: "dbt_nyc_metrics"
      database: "dbt_nyc_metrics"
      session_provisioning_timeout_in_seconds: 120
      location: "s3://ikoch-lakeformation-db/nyctaxi-data-out/"

